nginx:
  build: ./project-database-nginx
  links:
    - employee:employee
    - project:project
  ports:
    - "80:80"

employee:
  build: ./project-database-employee
  ports:
    - "8090:8090"

project:
  build: ./project-database-project
  ports:
    - "8091:8091"