eureka:
  build: ./project-database-eureka-server
  ports: 
    - "8092:8092"
  environment:
    - SPRING_PROFILES_ACTIVE=docker

hystrixdashboard:
  build: ./project-database-hystrix-dashboard
  ports:
    - "8094:8094"
  environment:
    - SPRING_PROFILES_ACTIVE=docker
  links:
    - eureka:eureka
    - project:project
    - employee:employee
    - gateway:gateway

project:
  build: ./project-database-project
  ports:
    - "8091:8091"
  environment:
    - SPRING_PROFILES_ACTIVE=docker
  links:
    - eureka:eureka
    - employee:employee

employee:
  build: ./project-database-employee
  ports:
    - "8090:8090"
  environment:
    - SPRING_PROFILES_ACTIVE=docker
  links:
    - eureka:eureka

gateway:
  build: ./project-database-api-gateway
  ports:
    - "8080:8080"
  environment:
    - SPRING_PROFILES_ACTIVE=docker
  links:
    - eureka:eureka
    - employee:employee
    - project:project