server:
 port: 8091

eureka:
 client:
  registerWithEureka: true
  fetchRegistry: true #https://github.com/spring-cloud/spring-cloud-netflix/issues/746
  serviceUrl:
   defaultZone: http://localhost:8092/eureka/
  healthcheck:
   enabled: true

---
spring:
  profiles: docker
eureka:
 client:
  registerWithEureka: true
  fetchRegistry: true 
  serviceUrl:
   defaultZone: http://${EUREKA_PORT_8092_TCP_ADDR}:8092/eureka/
 instance:
  preferIpAddress: true